#!/usr/bin/env python3
"""Turn the Kyria bottom-plate DXF into a coarse polyline for the wall pattern.

Writes kyria_outline.scad with `outline_chords`, a counter-clockwise closed
loop of [x, y] points. Straight DXF lines stay single chords; arcs are split
into chords no longer than CHORD_MAX. The main model still imports the DXF for
the exact profile; this polyline only tells it where the wall runs so the hex
pattern can be cut perpendicular to each chord.

Usage: python3 dxf2chords.py  (run from the project directory)
"""
import math
import sys

DXF = "Kyria rev3 Bottom Plate - No Kerf.dxf"
OUT = "kyria_outline.scad"
CHORD_MAX = 10.0   # mm
TOL = 1e-3         # endpoint matching tolerance


def read_entities(path):
    lines = [l.rstrip("\r\n") for l in open(path, encoding="latin-1")]
    pairs = [(lines[i].strip(), lines[i + 1].strip()) for i in range(0, len(lines) - 1, 2)]
    ents, cur, sec, in_ents = [], None, None, False
    for code, val in pairs:
        if code == "0" and val == "SECTION":
            sec = None
        if code == "2" and sec is None:
            sec = val
            in_ents = val == "ENTITIES"
            continue
        if not in_ents:
            continue
        if code == "0":
            if cur:
                ents.append(cur)
            cur = {"type": val}
        elif cur is not None:
            cur.setdefault(code, []).append(val)
    if cur:
        ents.append(cur)
    return ents


def segments(ents):
    """Each segment is a list of points in its natural direction."""
    segs = []
    for e in ents:
        g = lambda k: float(e[k][0])
        if e["type"] == "LINE":
            segs.append([(g("10"), g("20")), (g("11"), g("21"))])
        elif e["type"] == "ARC":
            cx, cy, r, a1, a2 = g("10"), g("20"), g("40"), g("50"), g("51")
            if a2 < a1:
                a2 += 360
            length = math.radians(a2 - a1) * r
            n = max(1, math.ceil(length / CHORD_MAX))
            pts = []
            for i in range(n + 1):
                a = math.radians(a1 + (a2 - a1) * i / n)
                pts.append((cx + r * math.cos(a), cy + r * math.sin(a)))
            segs.append(pts)
    return segs


def walk(segs):
    """Chain segments end to end into one closed loop of points."""
    used = [False] * len(segs)
    loop = list(segs[0])
    used[0] = True
    while True:
        cur = loop[-1]
        found = False
        for i, s in enumerate(segs):
            if used[i]:
                continue
            if math.dist(s[0], cur) < TOL:
                loop.extend(s[1:])
            elif math.dist(s[-1], cur) < TOL:
                loop.extend(reversed(s[:-1]))
            else:
                continue
            used[i] = True
            found = True
            break
        if not found:
            break
    if not all(used):
        sys.exit("outline did not chain into a single loop")
    if math.dist(loop[0], loop[-1]) > TOL:
        sys.exit("outline does not close")
    return loop[:-1]


def signed_area(pts):
    return sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(pts, pts[1:] + pts[:1])) / 2


def main():
    ents = read_entities(DXF)
    pts = walk(segments(ents))
    if signed_area(pts) < 0:
        pts.reverse()
    with open(OUT, "w") as f:
        f.write("// Generated by dxf2chords.py from %s -- do not edit.\n" % DXF)
        f.write("// Counter-clockwise closed loop; arcs split into chords <= %g mm.\n" % CHORD_MAX)
        f.write("outline_chords = [\n")
        for x, y in pts:
            f.write("    [%.4f, %.4f],\n" % (x, y))
        f.write("];\n")
    perim = sum(math.dist(a, b) for a, b in zip(pts, pts[1:] + pts[:1]))
    print("wrote %s: %d points, perimeter %.1f mm" % (OUT, len(pts), perim))


if __name__ == "__main__":
    main()
