// Tenting stand for a splitkb Kyria rev3 half.
//
// Two parts, one print:
//  * A collar in the keyboard's own frame: a wall perpendicular to the bottom
//    plate, following the case outline, with a small inward ledge the plate
//    rests on and a sloped underside below the ledge. The collar is tilted
//    with the keyboard.
//  * A pedestal below it with vertical walls, going straight down to the desk.
//    Its outer face is set in by `border`, so the collar overhangs it slightly
//    all around, as a design line. The pedestal carries the optional hex
//    pattern.
// No floor, no bottom. Prints upright without support.
//
// Needs the experimental roof() feature:
//   openscad --enable=roof -o kyria_stand_right.stl -D 'side="right"' kyria_stand.scad
// or just run ./build.sh. In the GUI enable "roof" under Preferences > Features.

// ---------- Parameters ----------------------------------------------------

// Which half. The DXF as drawn has the inner edge on -X; that is the right
// half seen from above. "left" mirrors the whole model.
side = "right"; // ["left", "right"]

inner_height  = 50;   // total height of the rim at the inner edge, above the desk (mm)
lip           = 4;    // collar wall above the plate's resting plane (mm)
collar_h      = 11;   // total collar height, lip included, measured along the keyboard (mm)
border        = 1;    // how far the collar overhangs the pedestal wall (mm)
wall          = 2;    // wall thickness, collar and pedestal (mm)
clearance     = 0.4;  // gap between case outline and pocket wall, per side (mm)
ledge_w       = 2.5;  // how far the ledge protrudes inward from the pocket wall (mm)
                      // keep <= 3: the nearest case screw is 5.3 mm from the edge
ledge_t       = 2.5;  // ledge thickness (mm)
chamfer_angle = 60;   // slope of the ledge underside, relative to the plate (deg)
outer_gap     = 0;    // lift of the collar's low corner off the desk (mm)

// Pedestal lightening pattern.
pattern       = "hex"; // ["none", "hex"]
hex_size      = 6;     // hole width, flat to flat (mm)
hex_strut     = 1.6;   // material left between holes (mm)
pattern_foot  = 3;     // solid band along the desk (mm)
pattern_top   = 1.5;   // solid margin below the collar (mm)
corner_margin = 3;     // solid material either side of a sharp corner (mm)
corner_deg    = 20;    // turn angle that counts as a sharp corner (deg)

dxf = "Kyria rev3 Bottom Plate - No Kerf.dxf";

// Coarse polyline of the same outline, generated by dxf2chords.py. Only used
// to place the wall pattern perpendicular to each chord of the wall.
include <kyria_outline.scad>

// Outline extents of the DXF (mm), used only to derive the tilt.
x_inner = -74.91;    // inner edge (OLED step + thumb cluster side)
x_outer =  85.89;    // outer edge (pinky side)

$fn = 96;

// ---------- Derived -------------------------------------------------------

collar_below = collar_h - lip;                 // collar depth below the plate
chamfer_h    = ledge_w * tan(chamfer_angle);   // height of the sloped underside

// Tent angle: the rim reaches inner_height at the outer face of the inner
// wall, and the collar's low outer corner sits on the desk (plus outer_gap).
// Solves A*sin(a) + B*cos(a) = C.
x_lo     = x_inner - clearance - wall;         // outer face of the inner wall
x_hi_out = x_outer + clearance + wall;         // outer face of the outer wall
A        = x_hi_out - x_lo;
B        = collar_h;
C        = inner_height - outer_gap;
tent_deg = asin(C / sqrt(A * A + B * B)) - atan2(B, A);
slope    = tan(tent_deg);

// Keyboard frame: plate plane through (0, 0, c_top), rotated tent_deg about Y.
c_top   = x_hi_out * sin(tent_deg) + collar_below * cos(tent_deg) + outer_gap;
// Collar/pedestal joint plane, in world coords: z = c_joint - slope * x
c_joint = c_top - collar_below / cos(tent_deg);

echo(str("tent angle = ", tent_deg, " deg"));
echo(str("outer rim height = ", collar_h * cos(tent_deg) + outer_gap,
         " mm, inner rim height = ", inner_height, " mm"));
echo(str("ledge underside slope, world: ", chamfer_angle - tent_deg, " to ",
         chamfer_angle + tent_deg, " deg from horizontal"));
if (collar_below < ledge_t + chamfer_h)
    echo(str("NOTE: collar_h is too small for the ledge chamfer; it gets truncated by ",
             ledge_t + chamfer_h - collar_below, " mm. Raise collar_h or lower chamfer_angle."));

BIG = 1000;

// ---------- 2D profiles ---------------------------------------------------

// Case outline with the M2 holes filled in (grow then shrink closes r=1.2 holes).
module plate_outline() {
    offset(delta = -2) offset(delta = 2) import(dxf);
}

module pocket_profile() { offset(r = clearance) plate_outline(); }
module outer_profile()  { offset(r = clearance + wall) plate_outline(); }
module inside_ledge()   { offset(r = -ledge_w) pocket_profile(); }

// ---------- Frames --------------------------------------------------------

// Keyboard frame -> world.
module frame() { translate([0, 0, c_top]) rotate([0, tent_deg, 0]) children(); }

// Where a 2D shape drawn on the collar's bottom plane lands on the desk,
// seen from above (the pedestal footprint).
module footprint() {
    translate([-collar_below * sin(tent_deg), 0]) scale([cos(tent_deg), 1]) children();
}

// Everything below the world plane z(x) = c - slope * x
module below(c) {
    multmatrix([[1, 0, 0, 0],
                [0, 1, 0, 0],
                [-slope, 0, 1, 0],
                [0, 0, 0, 1]])
        translate([-BIG / 2, -BIG / 2, c - BIG]) cube([BIG, BIG, BIG]);
}

// ---------- Collar (keyboard frame, plate plane at z = 0) -----------------

module collar_frame() {
    difference() {
        translate([0, 0, -collar_below]) linear_extrude(collar_h) outer_profile();
        // pocket above the plate
        linear_extrude(BIG) pocket_profile();
        // open middle, all the way through
        translate([0, 0, -BIG / 2]) linear_extrude(BIG) inside_ledge();
        // open below the ledge's sloped underside
        translate([0, 0, -BIG - ledge_t - chamfer_h]) linear_extrude(BIG) pocket_profile();
        // sloped underside: roof() rises at 45 deg from the pocket outline,
        // scaling z sets the chamfer angle
        translate([0, 0, -ledge_t - chamfer_h])
            scale([1, 1, chamfer_h / ledge_w]) roof() pocket_profile();
    }
}

// ---------- Pedestal (world frame, vertical walls) ------------------------

module pedestal() {
    difference() {
        intersection() {
            linear_extrude(BIG) footprint() offset(r = -border) outer_profile();
            below(c_joint);
        }
        translate([0, 0, -1]) linear_extrude(BIG) footprint() offset(r = -border) pocket_profile();
        if (pattern == "hex") wall_pattern();
    }
}

// ---------- Pedestal pattern ----------------------------------------------
//
// The pedestal wall is "unrolled" into (s, z) coordinates, s being distance
// along the footprint. A hex lattice is laid out in that plane, then for each
// chord of the footprint the strip of lattice over that chord is extruded
// through the wall along the chord's outward normal.

N = len(outline_chords);
function P(i) = let(q = outline_chords[((i % N) + N) % N])
    [q[0] * cos(tent_deg) - collar_below * sin(tent_deg), q[1]];   // same map as footprint()
function clen(i) = norm(P(i + 1) - P(i));
function cang(i) = atan2(P(i + 1)[1] - P(i)[1], P(i + 1)[0] - P(i)[0]);
function cum(i)  = i <= 0 ? 0 : cum(i - 1) + clen(i - 1);         // s at start of chord i
function turn(i) = let(d = cang(i) - cang(i - 1)) abs(((d + 540) % 360) - 180);  // turn at vertex i
function is_corner(i) = turn(i) > corner_deg;

perimeter = cum(N);
hex_r     = hex_size / sqrt(3);                       // circumradius of a hole
ncol      = round(perimeter / (hex_size + hex_strut));
pitch_s   = perimeter / ncol;                         // adjusted so the lattice closes on itself
pitch_z   = pitch_s * sqrt(3) / 2;
nrows     = ceil(inner_height / pitch_z) + 1;

// Lower edge of the solid band under the collar, at world x.
function z_limit(x) = c_joint - slope * x - pattern_top;

// 2D: lattice holes over chord i, in the chord's local (s, z) frame, clipped
// to the chord and kept away from sharp corners.
module hex_strip(i) {
    s0  = cum(i);
    L   = clen(i);
    a   = is_corner(i)     ? corner_margin : 0;
    b   = is_corner(i + 1) ? corner_margin : 0;
    ang = cang(i);
    if (L - a - b > 0.5)
        intersection() {
            translate([a, -1]) square([L - a - b, inner_height + 2]);
            for (j = [0 : nrows - 1], k = [-1 : ncol])
                let(sc = k * pitch_s + (j % 2) * pitch_s / 2 - s0,
                    zc = pattern_foot + hex_r + j * pitch_z,
                    xw = P(i)[0] + sc * cos(ang))          // world x of the hole centre
                if (sc > a - hex_size / 2 && sc < L - b + hex_size / 2
                    && zc + 0.25 * hex_r < z_limit(xw))     // skip holes the top band would reduce to slivers
                    translate([sc, zc]) rotate(30) circle(r = hex_r, $fn = 6);
        }
}

// 3D: the strip for chord i, extruded outward through the pedestal wall.
module wall_cutter(i) {
    A = P(i);
    translate([A[0], A[1], 0]) rotate([0, 0, cang(i)])
        translate([0, border + 1, 0])           // start inside the pedestal's inner face
            rotate([90, 0, 0])                  // 2D y -> z, extrude toward the outward normal
                linear_extrude(wall + clearance + 2) hex_strip(i);
}

module wall_pattern() {
    intersection() {
        union() for (i = [0 : N - 1]) wall_cutter(i);
        below(c_joint - pattern_top);
    }
}

// ---------- Assembly ------------------------------------------------------

module stand() {
    intersection() {
        union() {
            frame() collar_frame();
            pedestal();
        }
        translate([-BIG / 2, -BIG / 2, 0]) cube(BIG);   // the desk
    }
}

if (side == "left") mirror([1, 0, 0]) stand();
else stand();
