// Tenting stand for a splitkb Kyria rev3 half.
//
// Two parts, one print:
//  * A collar in the keyboard's own frame: a wall perpendicular to the bottom
//    plate, following the case outline, with a small inward ledge the plate
//    rests on and a sloped underside below the ledge. The collar is tilted
//    with the keyboard.
//  * A pedestal below it with vertical walls, going straight down to the desk.
//    Its outer face is set in by `border`, so the collar overhangs it slightly
//    all around, as a design line. The pedestal carries the optional hex
//    pattern.
// No floor, no bottom. Prints upright without support.
//
// Needs the experimental roof() feature:
//   openscad --enable=roof -o kyria_stand_right.stl -D 'side="right"' kyria_stand.scad
// or just run ./build.sh. In the GUI enable "roof" under Preferences > Features.

// ---------- Parameters ----------------------------------------------------

// Which half. The DXF as drawn has the inner edge on -X; that is the right
// half seen from above. "left" mirrors the whole model.
side = "right"; // ["left", "right"]

inner_height  = 40;   // total height of the rim at the inner edge, above the desk (mm)
lip           = 6;    // collar wall above the plate's resting plane (mm)
collar_extra  = 0;    // extra collar depth below the ledge chamfer (mm); 0 = as short as possible
border        = 1;    // how far the collar overhangs the pedestal wall (mm)
wall          = 2;    // wall thickness, collar and pedestal (mm)
clearance     = 0.4;  // gap between case outline and pocket wall, per side (mm)
ledge_w       = 2;    // how far the ledge protrudes inward from the pocket wall (mm)
                      // keep <= 3: the nearest case screw is 5.3 mm from the edge
ledge_t       = 1.5;  // ledge thickness (mm)
chamfer_angle = 57;   // slope of the ledge underside, relative to the plate (deg)
                      // printed overhang is chamfer_angle - tent angle from horizontal; keep >= 40
outer_gap     = 0;    // lift of the ledge underside off the desk at the outer edge (mm)

// Cable notches in the collar, as ranges in the DXF's coordinates. The
// controller strip runs along the inner edge, x -63..-30. The USB-C port
// points at the top edge (the edge facing away from you), centred about
// x = -42; the TRRS jack points out of the inner side edge at about y = 2.
// Both ranges are 16 mm, so they take any plug and a few mm of misjudgement.
notches_top   = [[-50, -34]]; // [x_from, x_to] through the top-edge wall; [] for none
notches_side  = [[-6, 10]];   // [y_from, y_to] through the inner-edge wall; [] for none
notch_depth   = 6;    // how far below the rim the notches go (mm); lip = down to the plate

// Pedestal lightening pattern.
pattern       = "hex"; // ["none", "hex", "voronoi"]
hex_size      = 6;     // hex: hole width, flat to flat (mm)
hex_strut     = 1.6;   // hex: material left between holes (mm)
voronoi_cell  = 10;    // voronoi: mean cell size (mm)
voronoi_strut = 1.6;   // voronoi: material left between cells (mm)
voronoi_jitter = 0.8;  // voronoi: 0 = regular grid, 1 = fully random within the grid
voronoi_seed  = 7;     // voronoi: change for a different random pattern
pattern_foot  = 3;     // solid band along the desk (mm)
pattern_top   = 0;     // solid margin below the collar (mm); 0 = holes run up to the collar
min_hole_h    = 1.5;   // drop holes the collar would cut down to less than this height (mm)
corner_margin = 0;     // solid material either side of a sharp corner (mm); 0 = pattern wraps around corners
corner_deg    = 20;    // turn angle that counts as a sharp corner (deg)

dxf = "Kyria rev3 Bottom Plate - No Kerf.dxf";

// Coarse polyline of the same outline, generated by dxf2chords.py. Only used
// to place the wall pattern perpendicular to each chord of the wall.
include <kyria_outline.scad>

// Outline extents of the DXF (mm), used only to derive the tilt.
x_inner = -74.91;    // inner edge (OLED step + thumb cluster side)
x_outer =  85.89;    // outer edge (pinky side)

$fn = 96;

// ---------- Derived -------------------------------------------------------

chamfer_h    = ledge_w * tan(chamfer_angle);   // height of the sloped underside
collar_below = ledge_t + chamfer_h + collar_extra;   // collar depth below the plate
collar_h     = lip + collar_below;

// Tent angle: the rim reaches inner_height at the outer face of the inner
// wall, and the ledge underside touches the desk at the outer edge of the
// pocket (plus outer_gap). Whatever hangs below the desk there is cut off.
// Solves A*sin(a) + B*cos(a) = C.
x_lo     = x_inner - clearance - wall;         // outer face of the inner wall
x_hi     = x_outer + clearance;                // pocket edge on the outer side
A        = x_hi - x_lo;
B        = ledge_t + lip;
C        = inner_height - outer_gap;
tent_deg = asin(C / sqrt(A * A + B * B)) - atan2(B, A);
slope    = tan(tent_deg);

// Keyboard frame: plate plane through (0, 0, c_top), rotated tent_deg about Y.
c_top   = x_hi * sin(tent_deg) + ledge_t * cos(tent_deg) + outer_gap;
// Collar/pedestal joint plane, in world coords: z = c_joint - slope * x
c_joint = c_top - collar_below / cos(tent_deg);

echo(str("tent angle = ", tent_deg, " deg"));
echo(str("plate bottom above desk at the outer edge = ", ledge_t * cos(tent_deg) + outer_gap, " mm"));
echo(str("collar height = ", collar_h, " mm; outer rim height = ",
         (ledge_t + lip) * cos(tent_deg) + outer_gap, " mm, inner rim height = ", inner_height, " mm"));
echo(str("ledge underside slope, world: ", chamfer_angle - tent_deg, " to ",
         chamfer_angle + tent_deg, " deg from horizontal"));

BIG = 1000;

// ---------- 2D profiles ---------------------------------------------------

// Case outline with the M2 holes filled in (grow then shrink closes r=1.2 holes).
module plate_outline() {
    offset(delta = -2) offset(delta = 2) import(dxf);
}

module pocket_profile() { offset(r = clearance) plate_outline(); }
module outer_profile()  { offset(r = clearance + wall) plate_outline(); }
module inside_ledge()   { offset(r = -ledge_w) pocket_profile(); }

// ---------- Frames --------------------------------------------------------

// Keyboard frame -> world.
module frame() { translate([0, 0, c_top]) rotate([0, tent_deg, 0]) children(); }

// Where a 2D shape drawn on the collar's bottom plane lands on the desk,
// seen from above (the pedestal footprint).
module footprint() {
    translate([-collar_below * sin(tent_deg), 0]) scale([cos(tent_deg), 1]) children();
}

// Everything below the world plane z(x) = c - slope * x
module below(c) {
    multmatrix([[1, 0, 0, 0],
                [0, 1, 0, 0],
                [-slope, 0, 1, 0],
                [0, 0, 0, 1]])
        translate([-BIG / 2, -BIG / 2, c - BIG]) cube([BIG, BIG, BIG]);
}

// ---------- Collar (keyboard frame, plate plane at z = 0) -----------------

module collar_frame() {
    difference() {
        translate([0, 0, -collar_below]) linear_extrude(collar_h) outer_profile();
        // pocket above the plate
        linear_extrude(BIG) pocket_profile();
        // open middle, all the way through
        translate([0, 0, -BIG / 2]) linear_extrude(BIG) inside_ledge();
        // open below the ledge's sloped underside
        translate([0, 0, -BIG - ledge_t - chamfer_h]) linear_extrude(BIG) pocket_profile();
        // sloped underside: roof() rises at 45 deg from the pocket outline,
        // scaling z sets the chamfer angle
        translate([0, 0, -ledge_t - chamfer_h])
            scale([1, 1, chamfer_h / ledge_w]) roof() pocket_profile();
        // cable notches: USB-C through the top-edge wall, TRRS through the inner wall
        for (n = notches_top)
            translate([n[0], 30, lip - notch_depth]) cube([n[1] - n[0], BIG, BIG]);
        for (n = notches_side)
            translate([-BIG - 60, n[0], lip - notch_depth]) cube([BIG, n[1] - n[0], BIG]);
    }
}

// ---------- Pedestal (world frame, vertical walls) ------------------------

module pedestal() {
    difference() {
        intersection() {
            linear_extrude(BIG) footprint() offset(r = -border) outer_profile();
            below(c_joint);
        }
        translate([0, 0, -1]) linear_extrude(BIG) footprint() offset(r = -border) pocket_profile();
        if (pattern != "none") wall_pattern();
    }
}

// ---------- Pedestal pattern ----------------------------------------------
//
// The pedestal wall is "unrolled" into (s, z) coordinates, s being distance
// along the footprint. A hex lattice is laid out in that plane, then for each
// chord of the footprint the strip of lattice over that chord is extruded
// through the wall along the chord's outward normal.

N = len(outline_chords);
function P(i) = let(q = outline_chords[((i % N) + N) % N])
    [q[0] * cos(tent_deg) - collar_below * sin(tent_deg), q[1]];   // same map as footprint()
function clen(i) = norm(P(i + 1) - P(i));
function cang(i) = atan2(P(i + 1)[1] - P(i)[1], P(i + 1)[0] - P(i)[0]);
function cum(i)  = i <= 0 ? 0 : cum(i - 1) + clen(i - 1);         // s at start of chord i
function sturn(i) = let(d = cang(i) - cang(i - 1)) ((d + 540) % 360) - 180;   // signed turn at vertex i
function turn(i) = abs(sturn(i));
function is_corner(i) = turn(i) > corner_deg;
function margin(i) = is_corner(i) ? corner_margin : 0;

// Range of s (chord-local) that chord i's cutter covers. With a margin the
// strip stops short of the corner; otherwise it runs past the chord end and
// the 3D mitre planes in wall_cutter() trim it, so holes fold around corners.
hole_ext = pattern == "voronoi" ? 2 * voronoi_cell : hex_size;
function s_lo(i) = margin(i) > 0 ? margin(i) : -hole_ext;
function s_hi(i) = margin(i + 1) > 0 ? clen(i) - margin(i + 1) : clen(i) + hole_ext;

perimeter = cum(N);
hex_r     = hex_size / sqrt(3);                       // circumradius of a hole
ncol      = round(perimeter / (hex_size + hex_strut));
pitch_s   = perimeter / ncol;                         // adjusted so the lattice closes on itself
pitch_z   = pitch_s * sqrt(3) / 2;
nrows     = ceil(inner_height / pitch_z) + 1;

// Lower edge of the solid band under the collar, at world x.
function z_limit(x) = c_joint - slope * x - pattern_top;

// 2D: lattice holes over chord i, in the chord's local (s, z) frame, clipped
// to the chord and kept away from sharp corners.
module hex_strip(i) {
    s0  = cum(i);
    lo  = s_lo(i);
    hi  = s_hi(i);
    ang = cang(i);
    if (hi - lo > 0.5)
        intersection() {
            translate([lo, -1]) square([hi - lo, inner_height + 2]);
            for (j = [0 : nrows - 1], k = [-2 : ncol + 1])
                let(sc = k * pitch_s + (j % 2) * pitch_s / 2 - s0,
                    zc = pattern_foot + hex_r + j * pitch_z,
                    xw = P(i)[0] + sc * cos(ang))          // world x of the hole centre
                if (sc > lo - hex_size / 2 && sc < hi + hex_size / 2
                    && z_limit(xw) - (zc - hex_r) > min_hole_h)   // skip holes the collar would cut to slivers
                    translate([sc, zc]) rotate(30) circle(r = hex_r, $fn = 6);
        }
}

// ---------- Voronoi variant ------------------------------------------------
//
// Seeds sit on a jittered hex grid over the whole unrolled wall (including
// the solid bands, so edge cells get proper neighbours). Each hole is the
// Voronoi cell of its seed, shrunk by half a strut. Seeds near the seam are
// mirrored across it so the pattern wraps seamlessly.

vor_cols    = max(1, round(perimeter / voronoi_cell));
vor_pitch_s = perimeter / vor_cols;
vor_pitch_z = voronoi_cell * sqrt(3) / 2;
vor_rows    = ceil((inner_height + 2 * voronoi_cell) / vor_pitch_z);
vor_n       = vor_rows * vor_cols;
vor_rand    = rands(-0.5, 0.5, 2 * vor_n, voronoi_seed);
function vor_seed(idx) = let(j = floor(idx / vor_cols), k = idx % vor_cols)
    [(k + (j % 2) * 0.5 + voronoi_jitter * vor_rand[2 * idx]) * vor_pitch_s,
     -voronoi_cell + (j + voronoi_jitter * vor_rand[2 * idx + 1]) * vor_pitch_z];
vor_seeds = [for (i = [0 : vor_n - 1]) vor_seed(i)];
vor_reach = 2.5 * voronoi_cell;                       // neighbours farther than this can't bound a cell
vor_ext   = concat(vor_seeds,
                   [for (q = vor_seeds) if (q[0] < vor_reach) q + [perimeter, 0]],
                   [for (q = vor_seeds) if (q[0] > perimeter - vor_reach) q - [perimeter, 0]]);
function vor_neighbours(p) = [for (q = vor_ext) if (norm(q - p) > 1e-6 && norm(q - p) < vor_reach) q];

// Points closer to p than to q, pulled back by half a strut.
module half_plane(p, q) {
    m = (p + q) / 2;
    d = q - p;
    translate(m) rotate(atan2(d[1], d[0]))
        translate([-BIG - voronoi_strut / 2, -BIG / 2]) square([BIG, BIG]);
}

module vor_cell(p) {
    intersection() {
        translate(p - [vor_reach, vor_reach]) square(2 * vor_reach);
        intersection_for(q = vor_neighbours(p)) half_plane(p, q);
    }
}

// How far the cell of p extends straight up (dir = 1) or down (dir = -1) from
// the seed: the nearest half-plane boundary crossed by the vertical through p.
function vor_extent(p, dir) = min(concat([vor_reach],
    [for (q = vor_neighbours(p)) let(d = q - p)
        if (d[1] * dir > 1e-6) (norm(d) - voronoi_strut) / 2 * norm(d) / abs(d[1])]));

// 2D: Voronoi holes over chord i, in the chord's local (s, z) frame.
module vor_strip(i) {
    s0  = cum(i);
    lo  = s_lo(i);
    hi  = s_hi(i);
    ang = cang(i);
    if (hi - lo > 0.5)
        intersection() {
            translate([lo, pattern_foot]) square([hi - lo, inner_height]);
            // keep every cell that shows at least min_hole_h between the foot
            // band and the collar, like the hex rule; the bands clip the rest
            for (p = vor_ext)
                let(sc = p[0] - s0, zc = p[1], xw = P(i)[0] + sc * cos(ang),
                    z_bot = max(zc - vor_extent(p, -1), pattern_foot),
                    z_top = min(zc + vor_extent(p, 1), z_limit(xw)))
                if (sc > lo - voronoi_cell && sc < hi + voronoi_cell
                    && z_top - z_bot > min_hole_h)
                    translate([-s0, 0]) vor_cell(p);
        }
}

// ---------- Cutting the pattern through the wall ----------------------------

module pattern_strip(i) {
    if (pattern == "hex") hex_strip(i);
    else if (pattern == "voronoi") vor_strip(i);
}

// 3D: the strip for chord i, extruded outward through the pedestal wall and
// trimmed at both ends by the mitre plane (corner bisector) shared with the
// neighbouring chord, so the two cutters meet without a gap or overlap.
module wall_cutter(i) {
    A = P(i);
    L = clen(i);
    translate([A[0], A[1], 0]) rotate([0, 0, cang(i)])
        intersection() {
            translate([0, border + 1, 0])       // start inside the pedestal's inner face
                rotate([90, 0, 0])              // 2D y -> z, extrude toward the outward normal
                    linear_extrude(wall + clearance + 2) pattern_strip(i);
            // keep the side of the start mitre that belongs to this chord
            rotate([0, 0, -sturn(i) / 2]) translate([0, -BIG / 2, -BIG / 2]) cube(BIG);
            // and the side of the end mitre
            translate([L, 0, 0]) rotate([0, 0, sturn(i + 1) / 2])
                translate([-BIG, -BIG / 2, -BIG / 2]) cube(BIG);
        }
}

module wall_pattern() {
    intersection() {
        union() for (i = [0 : N - 1]) wall_cutter(i);
        below(c_joint - pattern_top);
    }
}

// ---------- Assembly ------------------------------------------------------

module stand() {
    intersection() {
        union() {
            frame() collar_frame();
            pedestal();
        }
        translate([-BIG / 2, -BIG / 2, 0]) cube(BIG);   // the desk
    }
}

if (side == "left") mirror([1, 0, 0]) stand();
else stand();
